### ISSUE TITLE
Build 121

### ISSUE THREAD

**Issue by mrmlnc** [Shahiem/Maintenance#1]
The plugin has stopped working :(

**Clean install. Nothing is configured.**
**Installed:** Blog, Google Analytics, Plugin Maintenance

Left: Admin (Chrome) | Right: User (IE)

**Before:**
![zx9eank](https://cloud.githubusercontent.com/assets/7034281/3564447/16cc07fe-0a86-11e4-9660-ea454ee98971.png)

**After:**
![zdbzif6](https://cloud.githubusercontent.com/assets/7034281/3564448/188b680a-0a86-11e4-9e52-6cb0288bfa6f.png)

The disorder :)

**Comment by Shahiem** [comment]
Thank you for reporting this issue. It must be fixed now :) (update 1.0.5

**Comment by mrmlnc** [comment]
Unfortunately, a new problem:
`A widget class name 'ShahiemSeymor\Ckeditor\FormWidgets\Wysiwyg' has not been registered`

Return CKeditor? :)))
`
1.0.4:
    - Removed require ckeditor
`

**Comment by Shahiem** [comment]
Fixed, thank you
